"use strict";
exports.__esModule = true;
var assert_1 = require("assert");
var TreeNode_1 = require("./TreeNode");
var AdditionOperator_1 = require("./Operations/AdditionOperator");
var SubtractionOperator_1 = require("./Operations/SubtractionOperator");
var DivisionOperator_1 = require("./Operations/DivisionOperator");
var MultiplicationOperator_1 = require("./Operations/MultiplicationOperator");
var tree = new TreeNode_1.TreeNode(new DivisionOperator_1.DivisionOperator(), null, new TreeNode_1.TreeNode(new AdditionOperator_1.AdditionOperator(), null, new TreeNode_1.TreeNode(null, 7, null, null), new TreeNode_1.TreeNode(new MultiplicationOperator_1.MultiplicationOperator(), null, new TreeNode_1.TreeNode(new SubtractionOperator_1.SubtractionOperator(), null, new TreeNode_1.TreeNode(null, 3, null, null), new TreeNode_1.TreeNode(null, 2, null, null)), new TreeNode_1.TreeNode(null, 5, null, null))), new TreeNode_1.TreeNode(null, 6, null, null));
assert_1.strictEqual("((7 + ((3 - 2) x 5)) ÷ 6)", tree.toString());
assert_1.strictEqual(2, tree.result());
